services:
  # ============================= Services =============================
  auth-service:
    build:
      context: .
      dockerfile: JM-CompanyAuthService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-auth-service:latest
    image: jm/company-auth-service
    container_name: jm-service-auth
    profiles:
      - "all"
    ports:
      - "8180:8080"
    env_file:
#      - ./JM-CompanyAuthService/CompanyAuthService/.auth.env
      - ./.env
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-service:
    build:
      context: .
      dockerfile: JM-CompanyProfileService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-profile-service:latest
    image: jm/company-profile-service
    container_name: jm-service-profile
    profiles:
      - "all"
    ports:
      - "8181:8081"
    env_file:
#      - ./JM-CompanyProfileService/CompanyProfileService/.profile.env
      - ./.env
    environment:
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-db:5432/profile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-service:
    build:
      context: .
      dockerfile: JM-ApplicantDiscoveryService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-discovery-service:latest
    image: jm/company-discovery-service
    container_name: jm-service-discovery
    profiles:
      - "all"
    ports:
      - "8182:8082"
    env_file:
#      - ./JM-ApplicantDiscoveryService/ApplicantDiscoveryService/.discovery.env
      - ./.env
    environment:
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://discovery-db:5432/discovery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      discovery-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  jobpost-service:
    build:
      context: .
      dockerfile: JM-JobPostService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-jobpost-service:latest
    image: jm/company-jobpost-service
    container_name: jm-service-jobpost
    profiles:
      - "all"
    ports:
      - "8183:8083"
    env_file:
#      - ./JM-JobPostService/JobPostService/.jobpost.env
      - ./.env
    environment:
      SERVER_PORT: 8083
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://jobpost-db:5432/jobpost_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      jobpost-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8083/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  media-service:
    build:
      context: .
      dockerfile: JM-CompanyMediaService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-media-service:latest
    image: jm/company-media-service
    container_name: jm-service-media
    profiles:
      - "all"
    ports:
      - "8184:8084"
    env_file:
#      - ./JM-CompanyMediaService/CompanyMediaService/.media.env
      - ./.env
    environment:
      SERVER_PORT: 8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://media-db:5432/media_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      media-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8084/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  tag-service:
    build:
      context: .
      dockerfile: JM-SkillTagService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-tag-service:latest
    image: jm/company-tag-service
    container_name: jm-service-tag
    profiles:
      - "all"
    ports:
      - "8185:8085"
    env_file:
#      - ./JM-SkillTagService/SkillTagService/.tag.env
      - ./.env
    environment:
      SERVER_PORT: 8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://tag-db:5432/tag_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      tag-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8085/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  subscription-service:
    build:
      context: .
      dockerfile: JM-CompanySubscriptionService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-subscription-service:latest
    image: jm/company-subscription-service
    container_name: jm-service-subscription
    profiles:
      - "all"
    ports:
      - "8186:8086"
    env_file:
#      - ./JM-CompanySubscriptionService/CompanySubscriptionService/.subscription.env
      - ./.env
    environment:
      SERVER_PORT: 8086
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://subscription-db:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8086/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= Databases =============================
  auth-db:
    image: postgres:latest
    container_name: jm-db-auth
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-db:
    image: postgres:latest
    container_name: jm-db-profile
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5533:5432"
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d profile_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-db:
    image: postgres:latest
    container_name: jm-db-discovery
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5534:5432"
    environment:
      POSTGRES_DB: discovery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d discovery_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  jobpost-db:
    image: postgres:latest
    container_name: jm-db-jobpost
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5535:5432"
    environment:
      POSTGRES_DB: jobpost_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jobpost_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  media-db:
    image: postgres:latest
    container_name: jm-db-media
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5536:5432"
    environment:
      POSTGRES_DB: media_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d media_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  tag-db:
    image: postgres:latest
    container_name: jm-db-tag
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5537:5432"
    environment:
      POSTGRES_DB: tag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tag_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  subscription-db:
    image: postgres:latest
    container_name: jm-db-subscription
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5538:5432"
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d subscription_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  payment-db:
    image: postgres:latest
    container_name: jm-db-payment
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5539:5432"
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d transaction_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= REDIS =============================
  redis:
    image: redis:7-alpine
    container_name: jm-db-auth-redis
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "6479:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - job-manager