services:
  # ============================= Services =============================
  auth-service:
    build:
      context: .
      dockerfile: JM-CompanyAuthService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-auth-service:latest
    image: jm/company-auth-service
    container_name: jm-service-auth
    profiles:
      - "all"
    ports:
      - "8180:8180"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8180
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== OAUTH GOOGLE ===============
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8180/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-service:
    build:
      context: .
      dockerfile: JM-CompanyProfileService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-profile-service:latest
    image: jm/company-profile-service
    container_name: jm-service-profile
    profiles:
      - "all"
    ports:
      - "8181:8181"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8181
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-db:5432/profile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8181/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-service:
    build:
      context: .
      dockerfile: JM-ApplicantDiscoveryService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-discovery-service:latest
    image: jm/company-discovery-service
    container_name: jm-service-discovery
    profiles:
      - "all"
    ports:
      - "8182:8182"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8182
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://discovery-db:5432/discovery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      discovery-db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8182/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  jobpost-service:
    build:
      context: .
      dockerfile: JM-JobPostService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-jobpost-service:latest
    image: jm/company-jobpost-service
    container_name: jm-service-jobpost
    profiles:
      - "all"
    ports:
      - "8183:8183"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8183
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://jobpost-db:5432/jobpost_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      # Cloud
      CLOUDKAFKA_BROKERS: ${CLOUDKAFKA_BROKERS}
      CLOUDKAFKA_API_KEY: ${CLOUDKAFKA_API_KEY}
      CLOUDKAFKA_API_SECRET: ${CLOUDKAFKA_API_SECRET}
      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      SCHEMA_REGISTRY_KEY: ${SCHEMA_REGISTRY_KEY}
      SCHEMA_REGISTRY_SECRET: ${SCHEMA_REGISTRY_SECRET}
      # Docker Local
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      jobpost-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8183/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  media-service:
    build:
      context: .
      dockerfile: JM-CompanyMediaService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-media-service:latest
    image: jm/company-media-service
    container_name: jm-service-media
    profiles:
      - "all"
    ports:
      - "8184:8184"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8184
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://media-db:5432/media_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== MEDIA GCS ===============
      COMPANYMEDIA_GCS_BUCKET: ${COMPANYMEDIA_GCS_BUCKET}
      COMPANYMEDIA_GCS_UPLOAD_PREFIX: ${COMPANYMEDIA_GCS_UPLOAD_PREFIX}
      COMPANYMEDIA_GCS_SIGNED_URL_TTL_MINUTES: ${COMPANYMEDIA_GCS_SIGNED_URL_TTL_MINUTES}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      media-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8184/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  tag-service:
    build:
      context: .
      dockerfile: JM-SkillTagService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-tag-service:latest
    image: jm/company-tag-service
    container_name: jm-service-tag
    profiles:
      - "all"
    ports:
      - "8185:8185"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8185
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://tag-db:5432/tag_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      tag-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8185/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  subscription-service:
    build:
      context: .
      dockerfile: JM-CompanySubscriptionService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-subscription-service:latest
    image: jm/company-subscription-service
    container_name: jm-service-subscription
    profiles:
      - "all"
    ports:
      - "8186:8186"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8186
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://subscription-db:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8186/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  payment-service:
    build:
      context: .
      dockerfile: JM-CompanyPaymentService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-payment-service:latest
    image: jm/company-payment-service
    container_name: jm-service-payment
    profiles:
      - "all"
    ports:
      - "8187:8187"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8187
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5432/transaction_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== STRIPE ===============
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      transaction-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8187/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  notification-service:
    build:
      context: .
      dockerfile: JM-NotificationService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-notification-service:latest
    image: jm/company-notification-service
    container_name: jm-service-notification
    profiles:
      - "all"
    ports:
      - "8188:8188"
    env_file:
      - ./.env
    environment:
      SERVER_PORT: 8188
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # =============== KAFKA & SCHEMA REGISTRY ===============
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
      # =============== SECURITY ===============
      # Key Pair
      PUBLIC_KEY_B64: ${PUBLIC_KEY_B64}
      PRIVATE_KEY_B64: ${PRIVATE_KEY_B64}
      # Redis
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      # Jwe Config
      JWE_ISSUER: ${JWE_ISSUER}
      JWE_TEMP_TOKEN_TTL: ${JWE_TEMP_TOKEN_TTL}
      JWE_ACCESS_TOKEN_TTL: ${JWE_ACCESS_TOKEN_TTL}
      JWE_REFRESH_TOKEN_TTL: ${JWE_REFRESH_TOKEN_TTL}
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      notification-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8188/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager